### Create user
POST http://localhost:8080/users/create
Content-Type: application/json

{
  "id": 100000001,
  "username": "username1",
  "fullName": "User 1",
  "age": 20,
  "isActive": true
}


### Search users
GET http://localhost:8080/users/search?text=username&page=0&size=6
Content-Type: application/json